-- 拡張機能の生存報告テーブル
--
-- なぜ必要か
--   ある担当者の自動記録がゼロのとき、「送っていない」のか「拡張が動いていない」のかが
--   区別できなかった。実データで同じ時期にバージョン1.27と1.36が混在していた。
--   どの端末で拡張が生きているかが分からないままでは、漏れ率などの集計も信用できない。
--
-- 書き込み方
--   追記のみ（background.js の sendHeartbeat）。4時間おき＋ブラウザ起動時。
--   1端末あたり1日6件程度なので、履歴として残しても量は問題にならない。
--   履歴があることで「昨日は動いていたが今日は来ていない」が分かる。
--
-- Supabase SQL Editor に貼って実行する。

create table if not exists public.extension_heartbeats (
  id              bigint generated by default as identity primary key,
  reported_at     timestamptz not null default now(),
  install_id      text not null,              -- 端末・プロファイルごとのランダムID（個人情報は含まない）
  recruiter_name  text,                       -- 空なら担当者名が未設定のまま使われている
  ext_version     text,
  trigger_source  text,                       -- alarm / startup / install / update
  browser         text,
  last_scout_at   timestamptz,                -- その端末のローカル記録の最新時刻
  scouts_1d       integer,
  scouts_7d       integer,
  queued_supabase integer,                    -- 未送信で滞留している件数（0でないと取りこぼしの疑い）
  queued_gas      integer
);

create index if not exists extension_heartbeats_reported_at_idx
  on public.extension_heartbeats (reported_at desc);
create index if not exists extension_heartbeats_install_idx
  on public.extension_heartbeats (install_id, reported_at desc);

-- 他のテーブルと同じく、拡張機能が持つ公開鍵（anon）は書き込みだけできるようにする。
-- 読み出しは service_role（手元のターミナル）だけ。
alter table public.extension_heartbeats enable row level security;

drop policy if exists "extension can insert heartbeats" on public.extension_heartbeats;
create policy "extension can insert heartbeats"
  on public.extension_heartbeats for insert to anon with check (true);


-- ── 確認用のクエリ ────────────────────────────────────────────────────
-- ① 端末ごとの最新状態。「最後に生きていた時刻」が古い端末＝動いていない
--
-- select distinct on (install_id)
--        recruiter_name, ext_version, reported_at, last_scout_at,
--        scouts_1d, scouts_7d, queued_supabase, queued_gas
--   from public.extension_heartbeats
--  order by install_id, reported_at desc;
--
-- ② バージョンがばらけていないか
--
-- select ext_version, count(distinct install_id) as 端末数
--   from public.extension_heartbeats
--  where reported_at > now() - interval '3 days'
--  group by ext_version order by 2 desc;
--
-- ③ 担当者名が未設定のまま使われている端末
--
-- select distinct on (install_id) install_id, ext_version, reported_at
--   from public.extension_heartbeats
--  where coalesce(recruiter_name, '') = ''
--  order by install_id, reported_at desc;
